package page;

public enum DrawingMode {
	DRAW_LINE, DRAW_RECT, DRAW_ELLIPSE, DRAW_ROUNDRECT, DRAW_LINE_LENGTH,
	DRAW_POINTS, TEXT, SELECT,
	FILL_OFF, FILL_ON,
	LINE_1X, LINE_2X, LINE_5X,
	DRAW_LINE_ARROW1, DRAW_LINE_ARROW2,
}
